name: listfiles in js

on:
  workflow_dispatch:

jobs:
  list-png-files:
    runs-on: ubuntu-latest
    outputs:
      file: ${{ steps.set-files.outputs.file }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set files output
        id: set-files
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const files = fs.readdirSync('.').filter(file => file.endsWith('.png'));
            console.log(JSON.stringify(files));
            core.setOutput('file', files);
          
  check:
    needs: list-png-files
    runs-on: ubuntu-latest
    strategy:
        matrix:
            file: ${{ fromJson(needs.list-png-files.outputs.file) }}
    steps:
      - name: Display files
        uses: actions/github-script@v6
        with:
          script: |
            console.log('${{ matrix.file }}');
