name: Fetch Personal Repositories

on:
  push:
    branches:
      - main  # Replace with your default branch name

jobs:
  fetch-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install @octokit/rest node-fetch

      - uses: actions/github-script@v6
        with:
          script: |
            const { Octokit } = require('@octokit/rest');
            const myfetch = require('node-fetch');

            const octokit = new Octokit({
              auth: process.env.PERSONAL_ACCESS_TOKEN,
              request: {
                fetch: () => myFetch,
              },
            });

            octokit.repos
              .listForAuthenticatedUser({
                visibility: 'private',
              })
              .then(({ data }) => {
                data.forEach(repo => {
                  console.log(repo.name);
                });
              })
              .catch(error => {
                console.error(error);
                process.exit(1);
              });
